version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/inventory
      - JWT_SECRET=changeme
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  mongo-data:
