name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGISTRY }}/current-time:latest .
        

    - name: Push image
      run: |
        docker push ${{ env.REGISTRY }}/current-time:latest

env:
  REGISTRY: 173.249.48.147:5000
