name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure Docker for insecure registry
      run: |
        echo '{ "insecure-registries": ["173.249.48.147:5000"] }' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGISTRY }}/current-time:latest .
        

    - name: Push image
      run: |
        docker push ${{ env.REGISTRY }}/current-time:latest

    - name: Deploy container
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 173.249.48.147
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull 173.249.48.147:5000/current-time:latest
          docker rm -f current-time || true
          docker run -d --name current-time -p 80:80 173.249.48.147:5000/current-time:latest

env:
  REGISTRY: 173.249.48.147:5000
